### ISSUE TITLE
Package for Raspbian (Debian on RPI PI)

### ISSUE THREAD

**Issue by spartrekus** [wojtekka/ydpdict#2]
Hello,

I am not a fan of automake and automatic compilation methods. I would be happy to know if there is a precompiled/compiled debian package for RPI Raspbian (arm, RPI III model b)?

This would be helpful. 

School and education use a lot the PI, so ydpdict would be for education welcome.

Thank you so much in advance !!

**Comment by wojtekka** [comment]
It's a bit late and I hope you already managed to solve your problem. But for posterity -- on one of my RPis running a OSMC (based on Debian), a simple `apt install ydpdict` worked just fine. On another running Raspbian it was a matter of:
```
sudo apt install build-essential libncurses-dev
wget https://github.com/wojtekka/ydpdict/releases/download/1.0.4/ydpdict-1.0.4.tar.gz
tar xvf ydpdict-1.0.4.tar.gz
cd ydpdict-1.0.4
./configure
make
sudo make install
```
